### ISSUE TITLE
jeu de calcul mental

### ISSUE THREAD

**Issue by ChangkaiWANG** [IQPlay/backend#7]
on peut faire des opérations arithmétiques pour gagner un score avec difficulté adaptative

**Comment by ChangkaiWANG** [comment]
36h au total
12h pour chaque itération
Nombre d'itération : 3
4h/personne
3 développeurs sur la feature

Livraison prévue le 6 novembre

**Comment by ChangkaiWANG** [comment]
<img width="702" alt="image" src="https://github.com/user-attachments/assets/34a943db-9e50-41a5-8899-6b7139c37524">

**Comment by SamiLetellier** [comment]
Définir une première version minimaliste et fonctionnelle du jeu 

![IMG_4042](https://github.com/user-attachments/assets/81a78db6-9a31-4e28-af3f-ca81e058485d)
